sudo: required
language: python
dist: jammy

services:
 - postgresql
matrix:
  include:
    - python: "3.10"
      env: GS_VERSION=2.24.4
    - python: "3.10"
      env: GS_VERSION=2.27.2
    - python: "3.10"
      env: GS_VERSION=master
install:
  - sudo apt-get -qq -y update
  - mkdir gs
  - pushd gs
  - wget https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-runner/9.4.31.v20200723/jetty-runner-9.4.31.v20200723.jar
  - wget https://build.geoserver.org/geoserver/${GS_VERSION}/geoserver-${GS_VERSION}-latest-war.zip
  - unzip geoserver-${GS_VERSION}-latest-war.zip
  - popd
  - pip install .
  - pip install psycopg2
before_script:
  - /usr/local/lib/jvm/openjdk11/bin/java -Xmx1024m -Dorg.eclipse.jetty.server.webapp.parentLoaderPriority=true -jar gs/jetty-runner-9.4.31.v20200723.jar --path /geoserver gs/geoserver.war > /dev/null 2>&1 &
  - psql -U postgres -c "create extension postgis"
  - psql -U postgres -c "create database db;"
  - psql -U postgres -d db -c "create extension postgis"
  - psql -U postgres -c "alter user postgres with password 'postgres';"
  - sleep 30
script:
  - python setup.py test
notifications:
  email:
    on_success: never
    on_failure: never
branches:
  only:
    - master
